<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>ComicViewer.ico</ApplicationIcon>
    <InvariantGlobalization>false</InvariantGlobalization>
    <SatelliteResourceLanguages>en;zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <!-- 便携式单文件发布配置：dotnet publish -c Publish -r win-x64 -->
  <PropertyGroup Condition="'$(Configuration)' == 'Publish'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

</Project>

